package serialKirimData;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DecimalFormat;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RifqiTh0kz
 */
public class Monitor extends javax.swing.JFrame {

    Serial Serial = new Serial(this);

    /** Creates new form Monitor */
    public Monitor() {
        initComponents();
        jCommPort.setVisible(false);
        lPort.setVisible(false);
        bConn.setEnabled(false);
        btnKirim.setEnabled(false);
        txtRoll.setEnabled(false);
        txtDate.setEnabled(false);
        jLabel2.setEnabled(false);
        jLabel1.setEnabled(false);
        jCommPort.setEnabled(true);
        
        

        txtRoll.addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                if(txtRoll.isEnabled()){
                PopUpKeyboard keyboard = new Monitor.PopUpKeyboard(txtRoll);
                Point p = txtRoll.getLocationOnScreen();
                p.y += 30;
                keyboard.setLocation(p);
                keyboard.setVisible(true);
                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanSearch = new javax.swing.JPanel();
        jCommPort = new javax.swing.JComboBox();
        lPort = new javax.swing.JLabel();
        btnCariPort = new javax.swing.JButton();
        bConn = new javax.swing.JButton();
        btnKirim = new javax.swing.JButton();
        txtBerat = new javax.swing.JLabel();
        txtRoll = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Display Timbangan Buana Megah");
        setBackground(new java.awt.Color(0, 51, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanSearch.setName("jPanSearch"); // NOI18N
        jPanSearch.setLayout(null);

        jCommPort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCommPort.setName("jCommPort"); // NOI18N
        jPanSearch.add(jCommPort);
        jCommPort.setBounds(60, 10, 140, 30);

        lPort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lPort.setText("Port  :");
        lPort.setName("lPort"); // NOI18N
        jPanSearch.add(lPort);
        lPort.setBounds(10, 10, 60, 30);

        btnCariPort.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnCariPort.setText("Cari Port");
        btnCariPort.setName("btnCariPort"); // NOI18N
        btnCariPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPortActionPerformed(evt);
            }
        });
        jPanSearch.add(btnCariPort);
        btnCariPort.setBounds(20, 0, 160, 50);

        getContentPane().add(jPanSearch);
        jPanSearch.setBounds(10, 80, 210, 50);

        bConn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bConn.setText("Connect");
        bConn.setBorder(null);
        bConn.setName("bConn"); // NOI18N
        bConn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConnActionPerformed(evt);
            }
        });
        getContentPane().add(bConn);
        bConn.setBounds(30, 140, 160, 40);

        btnKirim.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnKirim.setText("Kirim Data");
        btnKirim.setName("btnKirim"); // NOI18N
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });
        getContentPane().add(btnKirim);
        btnKirim.setBounds(370, 10, 160, 70);

        txtBerat.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtBerat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtBerat.setText("0.0");
        txtBerat.setName("txtBerat"); // NOI18N
        getContentPane().add(txtBerat);
        txtBerat.setBounds(10, 20, 230, 40);

        txtRoll.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRoll.setName("txtRoll"); // NOI18N
        txtRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRollActionPerformed(evt);
            }
        });
        getContentPane().add(txtRoll);
        txtRoll.setBounds(340, 100, 59, 35);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tanggal :");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 140, 110, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel3.setText("Kg");
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 10, 90, 60);

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDate.setFormats("yyyy-MM-dd");
        txtDate.setName("txtDate"); // NOI18N
        getContentPane().add(txtDate);
        txtDate.setBounds(340, 140, 190, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("No. Roll :");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 100, 110, 29);

        setSize(new java.awt.Dimension(552, 230));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        if (Serial.getConnected() == true) {
            Serial.disconnect();
        }
    }//GEN-LAST:event_formWindowClosed
    
private void bConnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConnActionPerformed
// TODO add your handling code here:
    if (bConn.getText().equals("Connect")) {
        btnKirim.setEnabled(true);
        txtRoll.setEnabled(true);
        txtDate.setEnabled(true);
        jLabel2.setEnabled(true);
        jLabel1.setEnabled(true);
        jCommPort.setEnabled(false);
        Serial.connect();
        if (Serial.getConnected() == true) {
            if (Serial.initIOStream() == true) {
                Serial.initListener();
            }
        }
        //txtDataIn.getCursor();
    } else {
        if (Serial.getConnected() == true) {
            Serial.disconnect();
        }
        jCommPort.setVisible(false);
        lPort.setVisible(false);
        btnCariPort.setVisible(true);
        bConn.setEnabled(false);
        btnKirim.setEnabled(false);
        txtRoll.setEnabled(false);
        txtDate.setEnabled(false);
        jLabel2.setEnabled(false);
        jLabel1.setEnabled(false);
        jCommPort.setEnabled(true);
    }
}//GEN-LAST:event_bConnActionPerformed

private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
// TODO add your handling code here:
    txtRoll.setText("");
    txtDate.setDate(null);
    //Serial.kirimData((byte)'a');
}//GEN-LAST:event_btnKirimActionPerformed

    private void btnCariPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPortActionPerformed
        // TODO add your handling code here:
        
    jCommPort.removeAllItems();
    jCommPort.setVisible(true);
    lPort.setVisible(true);
    btnCariPort.setVisible(false);
    Serial.cekSerialPort();
    bConn.setEnabled(true);
    }//GEN-LAST:event_btnCariPortActionPerformed

    private void txtRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRollActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Monitor().setVisible(true);
            }
        });
    }
    private class PopUpKeyboard extends JDialog implements ActionListener
    {
        private JTextField txt;

        public PopUpKeyboard(JTextField txt)
        {
            this.txt = txt;
            setLayout(new GridLayout(4, 4));
            this.setTitle("Keypad");
            for(int i = 1; i <= 9; i++) createButton(Integer.toString(i));
            createButton("0");
            createButton("<-");
            createButton("OK");
            pack();
        }

        private void createButton(String label)
        {
            JButton btn = new JButton(label);
            btn.addActionListener(this);
            btn.setFocusPainted(false);
            btn.setPreferredSize(new Dimension(65, 65));
            Font font = btn.getFont();
            float size = font.getSize() + 14.0f;
            btn.setFont(font.deriveFont(size));
            add(btn);
        }

        @Override
        public void actionPerformed(ActionEvent e)
        {
            String actionCommand = e.getActionCommand();
            if(actionCommand.equals("<-")){
            txt.setText(txt.getText().substring(0,txt.getText().length()-1));
            }else if(actionCommand.equals("OK")){
            dispose();
            }else{
            txt.setText(txt.getText() + actionCommand);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bConn;
    private javax.swing.JButton btnCariPort;
    public javax.swing.JButton btnKirim;
    public javax.swing.JComboBox jCommPort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanSearch;
    private javax.swing.JLabel lPort;
    public javax.swing.JLabel txtBerat;
    private org.jdesktop.swingx.JXDatePicker txtDate;
    private javax.swing.JTextField txtRoll;
    // End of variables declaration//GEN-END:variables
}